language: python
rvm:
 - 3.6
before_install:
  - export PATH=./lammps_interface/bin:$PATH
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - python3 examples/water_on_slab/rutile110.py 
  - python3 examples/water_box/build.py
  - python3 examples/nanoparticle/wulff.py
