language: python
os:
  - linux
rvm:
  - 3.6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
before_install:
  - export PATH=./lammps_interface/bin:$PATH
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - python3 ./examples/water_on_slab/rutile_110.py 
  - python3 ./examples/water_box/build.py
  - cd ./examples/make_descriptors/
  - python3 ./test_rdf.py
  - cd ../read_rdf
  - python3 ./read_rdf.py
